
server:
  port: 9998
  ssl:
    enabled: true
    key-store: classpath:springboot.keystore
    key-store-type: PKCS12
    key-alias: springboot-https
    key-password: 123456
    key-store-password: 123456
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/v13?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123
  application:
    name: hh-demo
  task:
    execution:
      pool:
        core-size: 3
        max-size: 6
        keep-alive: 3s
        queue-capacity: 1000
  redis:
    host: 192.168.149
    database: 0
    port: 6379
    password: root
    connect-timeout: 3000   #毫秒
#        allow-core-thread-timeout: name
#  servlet:
#    multipart:
#      max-file-size: -1
#      max-requeest-size: -1
tempFilePath: F:/temp/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
    registry-fetch-interval-seconds: 30
    fetch-registry: false
    register-with-eureka: false
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
#mybatis:
#  mapper-locations:
#    - classpath:dao/*.xml
#    - classpath*:com/**/mapper/*.xml
ribbon:
  eureka:
    enabled: true
fegin:
  hystrix:
    enable: true
#定时任务开关
scheduling:
  cronTaskSwitch:
    enable: true
  task2Switch:
    enable: false
