spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: hh-demo       #路由id，命名随意，保持唯一性
          # 采用 LoadBalanceClient 方式请求，以 lb:// 开头，后面的是注册在eureka上的服务名
          uri: lb://hh-demo   #目标地址
          predicates:
            - Path=/demo/**   #路由规则
          filters:
            - StripPrefix=1
        - id: sso
          uri: lb://sso-web   #目标地址
          predicates:
              - Path=/sso/**   #路由规则
          filters:
            - StripPrefix=1  #去除前缀
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        #路由id，命名随意，保持唯一性
#      - id: hh-demo
#
#        uri: lb://hh-demo
#        predicates:
#        - Path=/demo/**
#      - id: sso
#        uri: lb://sso-web
#        predictes:
#        - Path=/sso/**
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
    registry-fetch-interval-seconds: 30
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
#ribbon:
#  eureka:
#    enabled: true
#zuul:
#  routes:
#    hh-demo:
#      path: /demo/**
#      serviceId: hh-demo
#    sso-web:
#      path: /sso/**
#      serviceId: sso-web
#    eureka-server:
#      path: /eureka/**
#      serviceId: eureka-server
